receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
      
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
      
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true

  debug:
    verbosity: detailed
    
processors:
  resource:
    attributes:
      - key: deployment.environment
        value: local
        action: upsert
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/tempo, debug]
      
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus, debug]
      
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp/loki, debug]