apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      serviceMap:
        datasourceUid: 'prometheus'
      tracesToMetrics:
        datasourceUid: 'prometheus'
    isDefault: true
    
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData: