source "https://rubygems.org"

ruby ">= 3.3", "< 3.5"

gem "sinatra", "~> 4.1"
gem "puma", "~> 6.0"

gem "opentelemetry-sdk", "~> 1.0"
gem "opentelemetry-exporter-otlp", "~> 0.30"
gem "opentelemetry-instrumentation-rack", "~> 0.31"
gem "opentelemetry-instrumentation-sinatra", "~> 0.30"